version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/MicroservicesAPI
hooks:
#  BeforeInstall:
#    - location: scripts/install_dependencies.sh
#      timeout: 300
#      runas: root
  ApplicationStart:
    - location: /var/www/html/MicroservicesAPI/scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: /var/www/html/MicroservicesAPI/scripts/stop_server.sh
      timeout: 300
      runas: root
