version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/MicroservicesAPI
  - source: /start_server.sh
    destination: /var/www/html/MicroservicesAPI/scripts
  - source: /stop_server.sh
    destination: /var/www/html/MicroservicesAPI/scripts
hooks:
#  BeforeInstall:
#    - location: scripts/install_dependencies.sh
#      timeout: 300
#      runas: root
  ApplicationStart:
    - location: /start_server.sh
      timeout: 30000
      runas: root
  ApplicationStop:
    - location: /stop_server.sh
      timeout: 30000
      runas: root
